# Generated by Django 5.2.6 on 2025-10-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_rental_brand_rental_category_rental_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
